export const deviceSchemas={ 
    DeviceTotalSchema : { schema: {
    description: 'Get the total number of devices',
    tags: ['Analytics: Devices'],
    response: {
        200: {
            type: 'object',
            properties: {
                total_devices: { type: 'number' }
            },
            required: ['total_devices']
        }
    }
}},
    DeviceStatusSchema : { schema: {
    description: 'Get the status of all devices',
    tags: ['Analytics: Devices'],
    response: {
        200: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    dispositive_id: { type: 'number' },
                    connected: { type: 'boolean' },
                    timestamp: { type: 'string', format: 'date-time' },
                    battery_level: { type: 'number' }
                },
                required: ['dispositive_id', 'connected', 'timestamp', 'battery_level']
            }
        }
    }
}},
DeviceIssuesOverTimeSchema : { schema: {
    description: 'Get the number of issues per device type over time',
    tags: ['Analytics: Devices'],
    response: {
        200: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    month: { type: 'string', format: 'date' },
                    type: { type: 'string' },
                    issue_count: { type: 'number' }
                },
                required: ['month', 'type', 'issue_count']
            }
        }
    }
}},
DeviceIssuesSchema : { schema: {
    description: 'Get the number of issues per device',
    tags: ['Analytics: Devices'],
    response: {
        200: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    dispositiveId: { type: 'number' },
                    _count: { type: 'object', properties: { id: { type: 'number' } }, required: ['id'] }
                },
                required: ['dispositiveId', '_count']
            }
        }
    }
}},
 DevicesSoldSchema : { schema: {
    description: 'Get the number of devices sold',
    tags: ['Analytics: Devices'],
    response: {
        200: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    sale_month: { type: 'string', format: 'date' },
                    devices_sold: { type: 'number' },
                    total_revenue: { type: 'number' }
                },
                required: ['sale_month', 'devices_sold', 'total_revenue']
            }
        }
    }
}},
DeviceRevenueSchema : { schema: {
    description: 'Get the revenue generated by devices',
    tags: ['Analytics: Devices'],
    response: {
        200: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    sale_period: { type: 'string' },
                    devices_sold: { type: 'number' },
                    total_revenue: { type: 'number' },
                    avg_device_price: { type: 'number' }
                },
                required: ['sale_period', 'devices_sold', 'total_revenue', 'avg_device_price']
            }
        }
    }
}},
MostPopularDevicesSchema : { schema: {
    description: 'Get the most popular devices',
    tags: ['Analytics: Devices'],
    response: {
        200: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    product_name: { type: 'string' },
                    total_devices: { type: 'number' },
                    sales_count: { type: 'number' },
                    total_revenue: { type: 'number' }
                },
                required: ['product_name', 'total_devices', 'sales_count', 'total_revenue']
            }
        }
    }
}},
DeviceInterventionSchema : { schema: {
    description: 'Get the number of interventions per device',
    tags: ['Analytics: Devices'],
    response: {
        200: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    intervention_month: { type: 'string', format: 'date' },
                    type: { type: 'string' },
                    intervention_count: { type: 'number' },
                    resolution_rate: { type: 'number' }
                },
                required: ['intervention_month', 'type', 'intervention_count', 'resolution_rate']
            }
        }
    }
}},
DevicePerformanceSchema: { schema: {
    description: 'Get the performance metrics of devices',
    tags: ['Analytics: Devices'],
    response: {
        200: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    device_id: { type: 'number' },
                    issues_count: { type: 'number' },
                    interventions_count: { type: 'number' },
                    avg_battery_level: { type: 'number' },
                },
                required: ['device_id', 'avg_battery_level', 'interventions_count']
            }
        }
    }
}}
}
